### ISSUE TITLE
Consider having conversions from AbstractArray infer size

### ISSUE THREAD

**Issue by tkoolen** [andyferris/StaticArrays.jl#10]
A little bit of convenience I initially expected from my use of FixedSizeArrays:
```julia
mat = [1 2; 3 4]
SMatrix(mat)
```
currently results in
```julia
ERROR: MethodError: no method matching size(::Type{StaticArrays.SMatrix})
Closest candidates are:
  size{T<:StaticArrays.StaticArray{T,N}}(::Union{T<:StaticArrays.StaticArray{T,N},Type{T<:StaticArrays.StaticArray}}, ::Integer) at <dir>/packages/v0.5/StaticArrays/src/abstractarray.jl:4
  size{N}(::Any, ::Integer, ::Integer, ::Integer...) at abstractarray.jl:30
  size(::BitArray{1}) at bitarray.jl:39
  ...
 in convert at <dir>/packages/v0.5/StaticArrays/src/core.jl:61 [inlined]
 in StaticArrays.SMatrix{S1,S2,T,L}(::Array{Int64,2}) at ./sysimg.jl:53
```
This works:
```julia
mat = [1 2; 3 4]
SMatrix{2, 2}(mat)
```
but it's a little annoying to have to specify the size parameters manually.

**Comment by tkoolen** [comment]
That's the last one for now. Thanks for your work! I think this will end up being quite an improvement over FixedSizeArrays.

**Comment by andyferris** [comment]
Thanks for all your bug-chasing and corner-case-catching, @tkoolen! :)

That one is a little tricky... currently it will steal the size parameters from another `StaticArray` but it assumes nothing else has a size defined on the type. So in some sense it is not trained to play nicely with other static array packages, and its hard to get good compatibility with `FixedSizeArrays` without explicitly importing it... I've tried to write it so that the functions are type stable - they simply won't work if they can't figure out the size properly. I'll look into this anyway - a better error message might be a good short-term solution/

At least there is a workaround in this case.  You can also try `using StaticArrays.FixedSizeArrays` for some compatibility-layer, but it's not designed for using both packages (FixedSizeArrays and StaticArrays) at once (and it is not tested).

**Comment by andyferris** [comment]
Oh, sorry I misinterpreted this one slightly (I thought of `Mat` from `FixedSizeArrays`).

Anyway, the plan is that *no*, you will not be allowed to do anything type-unstable, unless you try hard (e.g. `SMatrix{size(mat,1), size(mat,2)}(mat)`. If you are using this package, then you probably want/need your arrays to be faster than `Base.Array`. Doing what you suggest in the middle of a function would make it 10x slower than just using `Array`.

I'm deciding to close this issue for now - but thank you again (very much!) for your feedback, and let me know if you have any other issues.

**Comment by tkoolen** [comment]
Alright, that makes a lot of sense. I wasn't relying on this kind of conversion in anything performance critical, just as a convenience thing. Probably still best to not allow it in your code. It's easy enough to write a helper function yourself if need be.
And wow, you're quick. Thanks for taking care of all of these!
